import React from "react";
import SectionTitle from "./SectionTitle";
import { InputField } from "./InputField";

/**
 * LicenseTokenSection Component
 * 
 * Displays license token field matching backend Salon schema.
 * License token is required for new salons (generated by backend or entered manually).
 * In edit mode, license token is read-only as it's a unique identifier.
 */
const LicenseTokenSection = ({ data, onChange, onGenerate, isEditMode = false }) => {
  return (
    <section className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
      <SectionTitle
        label={{
          category: "License Token",
        }}
      />
      <div className="flex flex-col gap-4 md:flex-row justify-end">
        <div className="flex-1">
          <InputField
            label="License Token"
            required={!isEditMode}
            value={data.licenseToken}
            onChange={onChange("licenseToken")}
            placeholder={isEditMode ? "License token (read-only)" : "Enter or generate license token"}
            disabled={isEditMode}
          />
          {!isEditMode && (
            <p className="mt-1 text-xs text-gray-500">
              License token is a unique identifier for the salon. Generate automatically or enter manually.
            </p>
          )}
        </div>
        {!isEditMode && (
          <button
            type="button"
            onClick={onGenerate}
            className="flex items-center self-end h-fit justify-center gap-2 rounded-xl bg-indigo-600 px-6 py-2 text-sm font-semibold text-white shadow-lg shadow-indigo-500/30 transition hover:bg-indigo-500"
          >
            <span className="text-lg">↻</span> Generate
          </button>
        )}
      </div>
    </section>
  );
};

export default LicenseTokenSection;

